services:
  postgres:
    container_name: postgres_portfolio_v2
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-changname}
      POSTGRES_DB: ${DATABASE_NAME:-postgres}
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    expose:
      - '5432'
    volumes:
      - ./db:/data/postgres
    networks:
      - postgres

  adminer:
    container_name: adminer_portfolio_v2
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    networks:
      - postgres
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  adminer:
